package org.example.persion.service.impl;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.http.client.JdkClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.net.http.HttpClient;
import java.time.Duration;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Optional OpenAI-compatible wording layer.
 *
 * <p>All business/medical facts are generated by local tools first. The model is
 * allowed to rewrite those facts only. A post-generation grounding gate rejects
 * newly introduced numeric facts or medical-decision language and falls back to
 * the deterministic tool answer.</p>
 */
@Slf4j
@Component
public class MedicalAiModelEnhancer {

    private static final Pattern NUMBER_PATTERN = Pattern.compile("\\d+(?:\\.\\d+)?");
    private static final Set<String> BLOCKED_REWRITE_PHRASES = Set.of(
            "诊断为", "确诊为", "开处方", "处方建议", "用药建议", "建议服用", "建议停药",
            "建议换药", "调整剂量", "增加剂量", "减少剂量", "治疗方案"
    );

    @Value("${medical.ai.enabled:false}")
    private boolean enabled;

    @Value("${medical.ai.base-url:}")
    private String baseUrl;

    @Value("${medical.ai.api-key:}")
    private String apiKey;

    @Value("${medical.ai.model:}")
    private String model;

    @Value("${medical.ai.timeout-ms:5000}")
    private long timeoutMs;

    public Optional<String> enhance(String question, String factAnswer, List<String> sources) {
        if (!enabled || isBlank(baseUrl) || isBlank(model) || isBlank(factAnswer)) {
            return Optional.empty();
        }

        try {
            RestClient client = buildClient();
            RestClient.RequestBodySpec request = client.post()
                    .uri("/chat/completions")
                    .contentType(MediaType.APPLICATION_JSON);
            if (!isBlank(apiKey)) {
                request.header("Authorization", "Bearer " + apiKey.trim());
            }

            Map<String, Object> body = Map.of(
                    "model", model,
                    "temperature", 0.1,
                    "messages", List.of(
                            Map.of(
                                    "role", "system",
                                    "content", "你是医护工作台中的业务查询助手。只能重写用户提供的系统事实，禁止新增任何数字、事实、诊断、处方、用药调整或治疗建议。保持简洁，保留不确定性和数据时间范围。"
                            ),
                            Map.of(
                                    "role", "user",
                                    "content", "问题：" + safe(question) + "\n\n系统事实：\n" + factAnswer
                                            + "\n\n数据来源：" + String.join("；", sources == null ? List.of() : sources)
                            )
                    )
            );

            Map<?, ?> response = request.body(body).retrieve().body(Map.class);
            String content = extractContent(response);
            if (isBlank(content)) {
                return Optional.empty();
            }

            String rewrite = content.trim();
            if (!isSafeRewrite(rewrite, factAnswer)) {
                log.warn("Medical AI model rewrite rejected by grounding gate; using deterministic answer");
                return Optional.empty();
            }
            return Optional.of(rewrite);
        } catch (Exception exception) {
            // Never log the user question or tool facts: those may contain personal
            // or medical information.
            log.warn("Medical AI model enhancement failed; falling back to deterministic answer: {}",
                    exception.getClass().getSimpleName());
            return Optional.empty();
        }
    }

    /** Package-private for focused safety tests. */
    boolean isSafeRewrite(String rewrite, String factAnswer) {
        if (isBlank(rewrite) || isBlank(factAnswer)) {
            return false;
        }

        int maxLength = Math.max(600, factAnswer.length() * 2 + 200);
        if (rewrite.length() > maxLength) {
            return false;
        }

        for (String phrase : BLOCKED_REWRITE_PHRASES) {
            if (rewrite.contains(phrase)) {
                return false;
            }
        }

        Set<String> allowedNumbers = numbersIn(factAnswer);
        for (String number : numbersIn(rewrite)) {
            if (!allowedNumbers.contains(number)) {
                return false;
            }
        }
        return true;
    }

    private RestClient buildClient() {
        long boundedTimeout = Math.max(500, Math.min(timeoutMs, 30_000));
        Duration timeout = Duration.ofMillis(boundedTimeout);
        HttpClient httpClient = HttpClient.newBuilder()
                .connectTimeout(timeout)
                .build();
        JdkClientHttpRequestFactory requestFactory = new JdkClientHttpRequestFactory(httpClient);
        requestFactory.setReadTimeout(timeout);

        return RestClient.builder()
                .baseUrl(trimTrailingSlash(baseUrl))
                .requestFactory(requestFactory)
                .build();
    }

    private Set<String> numbersIn(String text) {
        Set<String> numbers = new HashSet<>();
        Matcher matcher = NUMBER_PATTERN.matcher(text == null ? "" : text);
        while (matcher.find()) {
            numbers.add(matcher.group());
        }
        return numbers;
    }

    private String extractContent(Map<?, ?> response) {
        if (response == null) return null;
        Object choicesObject = response.get("choices");
        if (!(choicesObject instanceof List<?> choices) || choices.isEmpty()) return null;
        Object firstObject = choices.get(0);
        if (!(firstObject instanceof Map<?, ?> first)) return null;
        Object messageObject = first.get("message");
        if (!(messageObject instanceof Map<?, ?> message)) return null;
        Object content = message.get("content");
        return content instanceof String ? (String) content : null;
    }

    private String trimTrailingSlash(String value) {
        String result = value.trim();
        while (result.endsWith("/")) result = result.substring(0, result.length() - 1);
        return result;
    }

    private String safe(String value) {
        return value == null ? "" : value;
    }

    private boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}
